language: ruby

rvm:
  — 2.6.5

cache:
  bundler: true
  directories:
    - node_modules

install:
  - bundle install --jobs 3 --retry 3

script:
  - bundle exec rubocop
  - rails dev:setup
  - bundle exec rspec
