language: ruby

rvm:
  — 2.6.5

cache:
  bundler: true
  directories:
    - node_modules

install:
  - bundle install --jobs 3 --retry 3

script:
  - bundle exec rubocop
  - chmod 777 db/test.sqlite3
  - bundle exec rspec --require spec_helper --require rails_helper
